
#African countries statistics in alphabetical order
#Area
#Population
#Capital
#GDP
#Main religion
#Fertility rate
#Mortality rate
#Life expectancy
#Currency
#Official language
Africa = {
        'Algeria': {
            'Area': '2,381,740 km square', 
            'Population': '46,731,000', 
            'Capital':'Algiers', 
            'GDP': '$187.155B', 
            'Main religion': 'Islam', 
            'Fertility rate': '3.1%', 
            'Mortality rate': '4.72%', 
            'Life expectancy': '77.13', 
            'Currency': 'Algerian dinar', 
            'Official language': 'Arabic'},
        'Angola': {
            'Area': '1,246,700 km square', 
            'Population': '32,866,272', 
            'Capital': 'Luanda', 
            'GDP': '$124.794B', 
            'Main religion': 'Christianity', 
            'Fertility rate': '5.6%', 
            'Mortality rate': '7.8%', 
            'Life expectancy': '61.93', 
            'Currency': 'Angolan kwanza', 
            'Official language': 'Portuguese'},
        'Benin': {
            'Area': '112,760 km square', 
            'Population': '12,123,200', 
            'Capital': 'Porto Novo', 
            'GDP': '$17.547B', 
            'Main religion': 'Christianity', 
            'Fertility rate': '4.9%', 
            'Mortality rate': '8.57%', 
            'Life expectancy': '59.95', 
            'Currency': 'CFA franc', 
            'Official language': 'French'},
        'Botswana': {
            'Area': '566,730 km square', 
            'Population':  '2,351,627', 
            'Capital': 'Gaborone', 
            'GDP': '$18.005B', 
            'Main religion': 'Christianity', 
            'Fertility rate': '2.9%', 
            'Mortality rate': '5.72%', 
            'Life expectancy': '65.91', 
            'Currency': 'Botswana pula', 
            'Official language': 'Setswana'},
        'Burkina Faso': {
            'Area': '273,600 km square', 
            'Population': '20,903,273', 
            'Capital': 'Ouagadougou', 
            'GDP': '$18.268B', 
            'Main religion': 'Islam', 
            'Fertility rate': '5.2%', 
            'Mortality rate': '7.71%', 
            'Life expectancy': '59.77', 
            'Currency': 'CFA franc', 
            'Official language': 'French'},
        'Burundi': {
                'Area': '25,680 km square', 
                'Population': '11,890,784', 
                'Capital': 'Bujumbura', 
                'GDP': '$3.686B', 
                'Main religion': 'Christianity', 
                'Fertility rate': '5.5%', 
                'Mortality rate': '7.61%', 
                'Life expectancy': '61.98', 
                'Currency': 'Burundian franc', 
                'Official language': 'Kirundi'},
        'Cameroon': {
                'Area': '472,710 km square',
                'Population': '26,545863',
                'Capital': 'Yaounde',
                'GDP': '$44.212B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.6%',
                'Mortality rate': '8.88%',
                'Life expectancy': '60.96',
                'Currency': 'CFA franc',
                'Official language': 'English'},
        'Cabo Verde': {
                'Area': '4,030 km square',
                'Population': '555,987',
                'Capital': 'Praia',
                'GDP': '$2.053B',
                'Main religion': 'Christianity',
                'Fertility rate': '2.3%',
                'Mortality rate': '5.54%',
                'Life expectancy': '74.72%',
                'Currency': 'Cape Verdean franc',
                'Official language': 'Portuguese'},
        'Central African Republic': {
                'Area': '622,980 km square',
                'Population': '4,829767',
                'Capital': 'Banjui',
                'GDP': '$2.488B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.8%',
                'Mortality rate': '11.72%',
                'Life expectancy': '54.48',
                'Currency': 'CFA franc',
                'Official language': 'French'},
        'Chad': {
                'Area': '1,259,200 km square',
                'Population': '11,890,784',
                'Capital': 'Bujumbura',
                'GDP': '$3.686B',
                'Main religion': 'Islam',
                'Fertility rate': '5.8%',
                'Mortality rate': '11.72%',
                'Life expectancy': '53',
                'Currency': 'CFA franc',
                'Official language': 'French'},
        'Comoros': {
                'Area': '1,861 km square',
                'Population': '869,601',
                'Capital': 'Bujumbura',
                'GDP': '$3.686B',
                'Main religion': 'Islam',
                'Fertility rate': '4.2%',
                'Mortality rate': '7.06%',
                'Life expectancy': '63.68',
                'Currency': 'Comorian franc',
                'Official language': 'Arabic'},
        "Cote d'Ivoire": {
                'Area': '318,000 km square',
                'Population': '26,378,274',
                'Capital': 'Yamoussoukro',
                'GDP': '$68.630B',
                'Main religion': 'Islam',
                'Fertility rate': '4.7%',
                'Mortality rate': '9.71%',
                'Life expectancy': '58.92',
                'Currency': 'CFA franc',
                'Official language': 'French'},
        'Djibouti': {
                'Area': '23,180 km square',
                'Population': '988,000',
                'Capital': 'Djibouti',
                'GDP': '$3.725B',
                'Main religion': 'Islam',
                'Fertility rate': '2.8%',
                'Mortality rate': '6.92%',
                'Life expectancy': '62.86',
                'Currency': 'Djiboutian franc',
                'Official language': 'French'},
        'Democratic Republic of the Congo': {
                'Area': '2,267,050 km square',
                'Population': '89,561,403',
                'Capital': 'Kinshasa',
                'GDP': '$63.909B',
                'Main religion': 'Christianity',
                'Fertility rate': '6.0%',
                'Mortality rate': '9.12%',
                'Life expectancy': '59.74',
                'Currency': 'Congolese franc',
                'Official language': 'French'},
        'Egypt': {
                'Area': '995,450 km square',
                'Population': '102,334,404',
                'Capital': 'Cairo',
                'GDP': '$469.094B',
                'Main religion': 'Islam',
                'Fertility rate': '3.3%',
                'Mortality rate': '5.75%',
                'Life expectancy': '70.16',
                'Currency': 'Egyptian pound',
                'Official language': 'Arabic'},
        'Equatorial Guinea': {
                'Area': '28,050 km square',
                'Population': '1,402,985',
                'Capital': 'Malabo',
                'GDP': '$16.877B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.6%',
                'Mortality rate': '8.91%',
                'Life expectancy': '61.19',
                'Currency': 'CFA franc',
                'Official language': 'Spanish'},
        'Eritrea': {
                'Area': '101,000km square',
                'Population': '1,160,164',
                'Capital': 'Asmara',
                'GDP': '$2.369B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.1%',
                'Mortality rate': '6.87%',
                'Life expectancy': '66.6',
                'Currency': 'Eritrean nakfa',
                'Official language': 'Tigrinya'},
        'Eswanti': {
                'Area': '17,200 km square',
                'Population': '1,160,164',
                'Capital': 'Mbabane',
                'GDP': '$4.669B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.0%',
                'Mortality rate': '8.88%',
                'Life expectancy': '56.36',
                'Currency': 'Lilangeni',
                'Official language': 'English'},
        'Ethiopia': {
                'Area': '1,000,000 km square',
                'Population': '114,963,588',
                'Capital': 'Addis Ababa',
                'GDP': '$111.181B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.3%',
                'Mortality rate': '6.29%',
                'Life expectancy': '65.65',
                'Currency': 'Ethiopian birr',
                'Official language': 'Amharic'},
        'Gabon': {
                'Area': '257,670 km square',
                'Population': '2,225,734',
                'Capital': 'Libreville',
                'GDP': '$22.221B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.0%',
                'Mortality rate': '6.6%',
                'Life expectancy': '65.69',
                'Currency': 'CFA franc',
                'Official language': 'French'},
        'Gambia': {
                'Area': '10,120 km square',
                'Population': '2,225,734',
                'Capital': 'Banjul',
                'GDP': '$2.172B',
                'Main religion': 'Islam',
                'Fertility rate': '5.3%',
                'Mortality rate': '7.55%',
                'Life expectancy': '62.91',
                'Currency': 'Dalasi',
                'Official language': 'English'},
        'Ghana': {
                'Area': '227,540 km square',
                'Population': '31,072,940',
                'Capital': 'Accra',
                'GDP': '$75.996B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.9%',
                'Mortality rate': '7.14%',
                'Life expectancy': '63.94',
                'Currency': 'Ghanian cedi',
                'Official language': 'English'},
        'Guinea': {
                'Area': '245,720 km square',
                'Population': '13,132,795',
                'Capital': 'Conakry',
                'GDP': '$19.745B',
                'Main religion': 'Islam',
                'Fertility rate': '4.7%',
                'Mortality rate': '8.03%',
                'Life expectancy': '58.98',
                'Currency': 'Guinean franc',
                'Official language': 'French'},
        'Guinea-Bissau': {
                'Area': '28,120 km square',
                'Population': '1,968,001',
                'Capital': 'Bissau',
                'GDP': '$1.624B',
                'Main religion': 'Islam',
                'Fertility rate': '4.5%',
                'Mortality rate': '9.27%',
                'Life expectancy': '59..86',
                'Currency': 'CFA Franc',
                'Official language': 'Portuguese'},
        'Kenya': {
                'Area': '569,140 km square',
                'Population': '53,771,296',
                'Capital': 'Nairobi',
                'GDP': '$114.858B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.5%',
                'Mortality rate': '5.34%',
                'Life expectancy': '62.05',
                'Currency': 'Kenyan shilling',
                'Official language': 'English'},
        'Lesotho': {
                'Area': '30,360 km square',
                'Population': '2,142,249',
                'Capital': 'Maseru',
                'GDP': '$2.507B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.2%',
                'Mortality rate': '13.69%',
                'Life expectancy': '53.04',
                'Currency': 'Lesotho loti',
                'Official language': 'Sesotho'},
        'Liberia': {
                'Area': '96,320 km square',
                'Population': '5,057,681',
                'Capital': 'Monrovia',
                'GDP': '$3.900B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.4%',
                'Mortality rate': '7.26%',
                'Life expectancy': '61.1',
                'Currency': 'Liberian dollar',
                'Official language': 'English'},
        'Libya': {
                'Area': '1,759,540 km square',
                'Population': '6,871,292',
                'Capital': 'Tripoli',
                'GDP': '$40.836B',
                'Main religion': 'Islam',
                'Fertility rate': '2.3%',
                'Mortality rate': '5.12%',
                'Life expectancy': '72.15',
                'Currency': 'Libyan dollar',
                'Official language': 'Arabic'},
        'Madagascar': {
                'Area': '581,795 km square',
                'Population': '27,691,018',
                'Capital': 'Antananarivo',
                'GDP': '$15.016B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.1%',
                'Mortality rate': '5.82%',
                'Life expectancy': '65.23',
                'Currency': 'Malagasy ariary',
                'Official language': 'French'},
        'Malawi': {
                'Area': '94,280 km square',
                'Population': '19,129952',
                'Capital': 'Lilongwe',
                'GDP': '$11.554B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.3%',
                'Mortality rate': '6.26%',
                'Life expectancy': '62.9',
                'Currency': 'Malawian kwacha',
                'Official language': 'English'},
        'Mali': {
                'Area': '1,220,190 km square',
                'Population': '20,250,833',
                'Capital': 'Bamako',
                'GDP': '$18.434B',
                'Main religion': 'Islam',
                'Fertility rate': '5.9%',
                'Mortality rate': '9.16%',
                'Life expectancy': '59.42',
                'Currency': 'CFA Franc',
                'Official language': 'French'},
        'Mauritania': {
                'Area': '1,030,700 km square',
                'Population': '4,649,658',
                'Capital': 'Nouakchott',
                'GDP': '$10.091B',
                'Main religion': 'Islam',
                'Fertility rate': '4.6%',
                'Mortality rate': '7.03%',
                'Life expectancy': '64.69',
                'Currency': 'Ouguiya',
                'Official language': 'Arabic'},
        'Mauritius': {
                'Area': '2,030 km square',
                'Population': '1,271,768',
                'Capital': 'Port Louis',
                'GDP': '$11.497B',
                'Main religion': 'Hinduism',
                'Fertility rate': '1.4%',
                'Mortality rate': '8.7%',
                'Life expectancy': '73.98',
                'Currency': 'Mauritian rupee',
                'Official language': 'English'},
        'Morocco': {
                'Area': '446,300 km square',
                'Population': '36,910,560',
                'Capital': 'Rabat',
                'GDP': '$142.874B',
                'Main religion': 'Islam',
                'Fertility rate': '2.4%',
                'Mortality rate': '5.06%',
                'Life expectancy': '74.97',
                'Currency': 'Moroccan dirham',
                'Official language': 'Arabic'},
        'Mozambique': {
                'Area': '786,380 km square',
                'Population': '31,255,435',
                'Capital': 'Maputo',
                'GDP': '$17.873B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.9%',
                'Mortality rate': '7.95%',
                'Life expectancy': '59.63',
                'Currency': 'Mozambican metical',
                'Official language': 'Portuguese'},
        'Namibia': {
                'Area': '823,290 km square',
                'Population': '2,540,905',
                'Capital': 'Windhoek',
                'GDP': '$12.488B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.4%',
                'Mortality rate': '7.73%',
                'Life expectancy': '58.06',
                'Currency': 'Namibian dollar',
                'Official language': 'English'},
        'Niger': {
                'Area': '1,266,700 km square',
                'Population': '24,206,644',
                'Capital': 'Niamey',
                'GDP': '$14.639B',
                'Main religion': 'Islam',
                'Fertility rate': '7.0%',
                'Mortality rate': '7.82%',
                'Life expectancy': '62.08',
                'Currency': 'CFA Franc',
                'Official language': 'French'},
        'Nigeria': {
                'Area': '910,700 km square', 
                'Population': '206,139,589', 
                'Capital': 'Abuja', 
                'GDP': '$504.203B', 
                'Main religion': 'Islam', 
                'Fertility rate': '5.4%', 
                'Mortality rate': '3.4%',
                'Life expectancy': '55.02', 
                'Currency': 'Nigerian naira', 
                'Official language': 'English'},
        'Republic of the Congo': {
                'Area': '341,500 km square',
                'Population': '5,518,087',
                'Capital': 'Brazzaville',
                'GDP': '$14.486B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.5%',
                'Mortality rate': '6.55%',
                'Life expectancy': '63.05',
                'Currency': 'CFA Franc',
                'Official language': 'French'},
        'Rwanda': {
                'Area': '24,670 km square',
                'Population': '12,952,218',
                'Capital': 'Kigali',
                'GDP': '$12.098B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.1%',
                'Mortality rate': '5.05%',
                'Life expectancy': '67.13',
                'Currency': 'Rwandan franc',
                'Official language': 'Rwanda'},
        'Sao Tome and Principe': {
                'Area': '960 km square',
                'Population': '219,159',
                'Capital': 'Sao Tome',
                'GDP': '$506M',
                'Main religion': 'Christianity',
                'Fertility rate': '4.4%',
                'Mortality rate': '4.71%',
                'Life expectancy': '68.79',
                'Currency': 'Sao Tome and Principe dobra',
                'Official language': 'Portuguese'},
        'Senegal': {
                'Area': '192,530 km square',
                'Population': '16,743,927',
                'Capital': 'Dakar',
                'GDP': '$27.542B',
                'Main religion': 'Islam',
                'Fertility rate': '4.7%',
                'Mortality rate': '5.48%',
                'Life expectancy': '67.91',
                'Currency': 'CFA Franc',
                'Official language': 'French'},
        'Seychelles': {
                'Area': '460 km square',
                'Population': '98,347',
                'Capital': 'Victoria',
                'GDP': '$2.005B',
                'Main religion': 'Christianity',
                'Fertility rate': '2.5%',
                'Mortality rate': '6.8%',
                'Life expectancy': '71.74',
                'Currency': 'Seychellois rupee',
                'Official language': 'English'},
        'Sierra Leone': {
                'Area': '72,180 km square',
                'Population': '7,976,983',
                'Capital': 'Freetown',
                'GDP': '$4.101B',
                'Main religion': 'Islam',
                'Fertility rate': '4.3%',
                'Mortality rate': '11.3%',
                'Life expectancy': '60.41',
                'Currency': 'Sierra Leonean leone',
                'Official language': 'English'},
        'Somalia': {
                'Area': '627,340 km square',
                'Population': '15,893,222',
                'Capital': 'Mogadishu',
                'GDP': '$8.416B',
                'Main religion': 'Islam',
                'Fertility rate': '6.1%',
                'Mortality rate': '10.5%',
                'Life expectancy': '56.11',
                'Currency': 'Somali shilling',
                'Official language': 'Somali'},
        'South Africa': {
                'Area': '1,213,090 km square',
                'Population': '59,308,690',
                'Capital': 'Pretoria',
                'GDP': '$411.480B',
                'Main religion': 'Christianity',
                'Fertility rate': '2.4%',
                'Mortality rate': '9.38%',
                'Life expectancy': '61.48',
                'Currency': 'South African rand',
                'Official language': 'Afrikaans'},
        'South Sudan': {
                'Area': '610,952 km square',
                'Population': '11,193,725',
                'Capital': 'Juba',
                'GDP': '$4.784B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.7%',
                'Mortality rate': '10.22%',
                'Life expectancy': '55.57',
                'Currency': 'South Sudanese pound',
                'Official language': 'English'},
        'Sudan': {
                'Area': '1,765,048 km square',
                'Population': '43,849,260',
                'Capital': 'Khartoum',
                'GDP': '$42.762B',
                'Main religion': 'Islam',
                'Fertility rate': '4.4%',
                'Mortality rate': '7.05%',
                'Life expectancy': '65.58',
                'Currency': 'Sudanese pound',
                'Official language': 'Arabic'},
        'Tanzania': {
                'Area': '885,800 km square',
                'Population': '59,734,218',
                'Capital': 'Dodoma',
                'GDP': '$76.582B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.9%',
                'Mortality rate': '6.12%',
                'Life expectancy': '66.78',
                'Currency': 'Tanzanian shilling',
                'Official language': 'Kiswahili'},
        'Togo': {
                'Area': '54,390 km square',
                'Population': '8,278,724',
                'Capital': 'Lome',
                'GDP': '$8.359B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.4%',
                'Mortality rate': '8.2%',
                'Life expectancy': '61.59',
                'Currency': 'CFA Franc',
                'Official language': 'French'},
        'Tunisia': {
                'Area': '155,360 km square',
                'Population': '11,818,619',
                'Capital': 'Tunis',
                'GDP': '$46.282B',
                'Main religion': 'Islam',
                'Fertility rate': '2.2%',
                'Mortality rate': '6.26%',
                'Life expectancy': '74.26',
                'Currency': 'Tunisian dinar',
                'Official language': 'Arabic'},
        'Uganda': {   
                'Area': '199,810 km square',
                'Population': '45,741,007',
                'Capital': 'Kampala',
                'GDP': '$48.352B',
                'Main religion': 'Christianity',
                'Fertility rate': '5.0%',
                'Mortality rate': '6.24%',
                'Life expectancy': '63.64',
                'Currency': 'Ugandan shilling',
                'Official language': 'English'},
        'Zambia': {
                'Area': '743,390 km square',
                'Population': '18,383,955',
                'Capital': 'Lusaka',
                'GDP': '$27.025B',
                'Main religion': 'Christianity',
                'Fertility rate': '4.7%',
                'Mortality rate': '6.22%',
                'Life expectancy': '61.8',
                'Currency': 'Zambian kwacha',
                'Official language': 'English'},
        'Zimbabwe': {
                'Area': '386,850 km square',
                'Population': '14,862,924',
                'Capital': 'Harare',
                'GDP': '$38.280B',
                'Main religion': 'Christianity',
                'Fertility rate': '3.6%',
                'Mortality rate': '7.69%',
                'Life expectancy': '59.39',
                'Currency': 'RTGS dollar',
                'Official language': 'English'}}
print(len(Africa))
